version: "{build}"

# Uncomment to debug via RDP
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - AppVeyor DownloadFile http://download.virtualbox.org/virtualbox/5.0.14/VirtualBox-5.0.14-105127-Win.exe
  - .\VirtualBox-5.0.14-105127-Win.exe -s -l -msiparams ADDLOCAL=VBoxApplication,VBoxUSB,VBoxNetworkAdp REBOOT=ReallySuppress
    #  - .\VirtualBox-5.0.14-105127-Win.exe -s -l -msiparams REBOOT=ReallySuppress
  #- AppVeyor DownloadFile https://github.com/StefanScherer/boot2docker/releases/download/v1.9.1-386/docker-machine-Windows-x86_64.exe
  #- copy docker-machine-Windows-x86_64.exe docker-machine.exe
  - AppVeyor DownloadFile https://github.com/StefanScherer/boot2docker/releases/download/v1.10.1-386/docker-machine-Windows-i386.exe
  - copy docker-machine-Windows-i386.exe docker-machine.exe

test_script:
  - .\docker-machine.exe -D create -d virtualbox --virtualbox-no-vtx-check --virtualbox-nictype "Am79C973" --virtualbox-hostonly-nictype "Am79C973" --virtualbox-boot2docker-url https://github.com/StefanScherer/boot2docker/releases/download/v1.9.1-386/boot2docker.iso dev
  - .\docker-machine.exe ls
  - .\docker-machine.exe env --shell powershell dev
  - ${ProgramFiles}\Oracle\VirtualBox\VBoxManage.exe controlvm dev screenshotpng screenshot.png

artifacts:
  - path: screenshot.png
    name: Release
